version: "3.8"

services:
  zookeeper:
    image: zookeeper:3.6
    container_name: druid-zookeeper
    ports:
      - "2181:2181"

  postgres:
    image: postgres:13
    container_name: druid-postgres
    environment:
      POSTGRES_PASSWORD: druid
      POSTGRES_USER: druid
      POSTGRES_DB: druid
    ports:
      - "5432:5432"

  druid-coordinator:
    image: apache/druid:28.0.1
    container_name: druid-coordinator
    platform: linux/amd64
    depends_on: [zookeeper, postgres]
    ports:
      - "8081:8081"
    command: coordinator
    deploy:
      resources:
        limits:
          memory: 1g

  druid-overlord:
    image: apache/druid:28.0.1
    container_name: druid-overlord
    platform: linux/amd64
    depends_on: [zookeeper, postgres]
    ports:
      - "8090:8090"
    command: overlord
    deploy:
      resources:
        limits:
          memory: 1g

  druid-broker:
    image: apache/druid:28.0.1
    container_name: druid-broker
    platform: linux/amd64
    depends_on: [zookeeper, druid-coordinator,postgres,druid-historical]
    ports:
      - "8082:8082"
    command: broker
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g



  druid-historical:
    image: apache/druid:28.0.1
    container_name: druid-historical
    platform: linux/amd64
    depends_on: [zookeeper, druid-coordinator]
    command: historical
    deploy:
      resources:
        limits:
          memory: 1g

  druid-middlemanager:
    image: apache/druid:28.0.1
    container_name: druid-middlemanager
    platform: linux/amd64
    depends_on: [zookeeper, druid-overlord]
    command: middleManager
    deploy:
      resources:
        limits:
          memory: 1g

  druid-router:
    image: apache/druid:28.0.1
    container_name: druid-router
    platform: linux/amd64
    depends_on: [druid-broker, druid-coordinator]
    ports:
      - "8880:8888"
    command: router
    environment:
      - DRUID_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 1g
